version: '3.8'

services:
  web:
    build: .
    container_name: zen_invest_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python zen_invest_snap/manage.py runserver 0.0.0.0:8000
    restart: always
