# Generated by Django 4.2.11 on 2026-01-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source',
            field=models.CharField(choices=[('GBM', 'GBM'), ('BITSO', 'Bitso'), ('NU', 'Nu'), ('MERCADO_PAGO', 'Mercado Pago'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
