# Generated by Django 4.2.11 on 2026-01-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_asset_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='latest_quantity',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
