# Generated by Django 4.2.11 on 2026-01-30 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_asset_latest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliovalue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_values', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(help_text='e.g., AAPL, BTC, MXN', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliovalue',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('user', 'ticker')},
        ),
        migrations.AlterUniqueTogether(
            name='portfoliovalue',
            unique_together={('user', 'date')},
        ),
    ]
