# Generated by Django 4.2.11 on 2026-10-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_asset_user_portfoliovalue_user_transaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysnapshot',
            name='currency_normalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfoliovalue',
            name='currency_normalized',
            field=models.BooleanField(default=False),
        ),
    ]
